import type { QueryOperationTypes as PgAdapterQueryOps } from "@prisma-next/adapter-postgres/operation-types";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma-next/contract/types";
import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from "@prisma-next/sql-contract/types";
// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as PgTypes } from "@prisma-next/target-postgres/codec-types";
import type { JsonValue } from "@prisma-next/target-postgres/codec-types";
import type { Char } from "@prisma-next/target-postgres/codec-types";
import type { Varchar } from "@prisma-next/target-postgres/codec-types";
import type { Numeric } from "@prisma-next/target-postgres/codec-types";
import type { Bit } from "@prisma-next/target-postgres/codec-types";
import type { VarBit } from "@prisma-next/target-postgres/codec-types";
import type { Timestamp } from "@prisma-next/target-postgres/codec-types";
import type { Timestamptz } from "@prisma-next/target-postgres/codec-types";
import type { Time } from "@prisma-next/target-postgres/codec-types";
import type { Timetz } from "@prisma-next/target-postgres/codec-types";
import type { Interval } from "@prisma-next/target-postgres/codec-types";

export type StorageHash =
  StorageHashBase<"sha256:c77620a3a08aaa9b71dc944efeff321c715b3218ce0ee3b66dda355074c3d752">;
export type ExecutionHash =
  ExecutionHashBase<"sha256:fe2a461b225432b9c5614bb3afabf6e1cff56d24ecd4647e40396f6f66a51d53">;
export type ProfileHash =
  ProfileHashBase<"sha256:1a8dbe044289f30a1de958fe800cc5a8378b285d2e126a8c44b58864bac2c18e">;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<
  CodecId extends string,
  _Encoded,
> = CodecId extends keyof CodecTypes ? CodecTypes[CodecId]["output"] : _Encoded;

export type FieldOutputTypes = {
  readonly ContactForm: {
    readonly id: CodecTypes["pg/int4@1"]["output"];
    readonly name: CodecTypes["pg/text@1"]["output"];
    readonly email: CodecTypes["pg/text@1"]["output"];
    readonly phone: CodecTypes["pg/text@1"]["output"] | null;
    readonly message: CodecTypes["pg/text@1"]["output"];
    readonly status: CodecTypes["pg/text@1"]["output"];
    readonly createdAt: CodecTypes["pg/timestamptz@1"]["output"];
    readonly updatedAt: CodecTypes["pg/timestamptz@1"]["output"];
  };
  readonly Post: {
    readonly id: CodecTypes["pg/int4@1"]["output"];
    readonly title: CodecTypes["pg/text@1"]["output"];
    readonly content: CodecTypes["pg/text@1"]["output"] | null;
    readonly authorId: CodecTypes["pg/int4@1"]["output"];
    readonly createdAt: CodecTypes["pg/timestamptz@1"]["output"];
    readonly updatedAt: CodecTypes["pg/timestamptz@1"]["output"];
  };
  readonly User: {
    readonly id: CodecTypes["pg/int4@1"]["output"];
    readonly email: CodecTypes["pg/text@1"]["output"];
    readonly username: CodecTypes["pg/text@1"]["output"] | null;
    readonly name: CodecTypes["pg/text@1"]["output"] | null;
    readonly createdAt: CodecTypes["pg/timestamptz@1"]["output"];
    readonly updatedAt: CodecTypes["pg/timestamptz@1"]["output"];
  };
  readonly Waitlist: {
    readonly id: CodecTypes["pg/int4@1"]["output"];
    readonly email: CodecTypes["pg/text@1"]["output"];
    readonly status: CodecTypes["pg/text@1"]["output"];
    readonly createdAt: CodecTypes["pg/timestamptz@1"]["output"];
    readonly updatedAt: CodecTypes["pg/timestamptz@1"]["output"];
  };
};
export type FieldInputTypes = {
  readonly ContactForm: {
    readonly id: CodecTypes["pg/int4@1"]["input"];
    readonly name: CodecTypes["pg/text@1"]["input"];
    readonly email: CodecTypes["pg/text@1"]["input"];
    readonly phone: CodecTypes["pg/text@1"]["input"] | null;
    readonly message: CodecTypes["pg/text@1"]["input"];
    readonly status: CodecTypes["pg/text@1"]["input"];
    readonly createdAt: CodecTypes["pg/timestamptz@1"]["input"];
    readonly updatedAt: CodecTypes["pg/timestamptz@1"]["input"];
  };
  readonly Post: {
    readonly id: CodecTypes["pg/int4@1"]["input"];
    readonly title: CodecTypes["pg/text@1"]["input"];
    readonly content: CodecTypes["pg/text@1"]["input"] | null;
    readonly authorId: CodecTypes["pg/int4@1"]["input"];
    readonly createdAt: CodecTypes["pg/timestamptz@1"]["input"];
    readonly updatedAt: CodecTypes["pg/timestamptz@1"]["input"];
  };
  readonly User: {
    readonly id: CodecTypes["pg/int4@1"]["input"];
    readonly email: CodecTypes["pg/text@1"]["input"];
    readonly username: CodecTypes["pg/text@1"]["input"] | null;
    readonly name: CodecTypes["pg/text@1"]["input"] | null;
    readonly createdAt: CodecTypes["pg/timestamptz@1"]["input"];
    readonly updatedAt: CodecTypes["pg/timestamptz@1"]["input"];
  };
  readonly Waitlist: {
    readonly id: CodecTypes["pg/int4@1"]["input"];
    readonly email: CodecTypes["pg/text@1"]["input"];
    readonly status: CodecTypes["pg/text@1"]["input"];
    readonly createdAt: CodecTypes["pg/timestamptz@1"]["input"];
    readonly updatedAt: CodecTypes["pg/timestamptz@1"]["input"];
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = ContractType<
  {
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: "__unbound__";
        readonly kind: "sql-namespace";
        readonly tables: {
          readonly contactForm: {
            columns: {
              readonly id: {
                readonly nativeType: "int4";
                readonly codecId: "pg/int4@1";
                readonly nullable: false;
                readonly default: {
                  readonly kind: "function";
                  readonly expression: "autoincrement()";
                };
              };
              readonly name: {
                readonly nativeType: "text";
                readonly codecId: "pg/text@1";
                readonly nullable: false;
              };
              readonly email: {
                readonly nativeType: "text";
                readonly codecId: "pg/text@1";
                readonly nullable: false;
              };
              readonly phone: {
                readonly nativeType: "text";
                readonly codecId: "pg/text@1";
                readonly nullable: true;
              };
              readonly message: {
                readonly nativeType: "text";
                readonly codecId: "pg/text@1";
                readonly nullable: false;
              };
              readonly status: {
                readonly nativeType: "text";
                readonly codecId: "pg/text@1";
                readonly nullable: false;
                readonly default: {
                  readonly kind: "literal";
                  readonly value: DefaultLiteralValue<"pg/text@1", "pending">;
                };
              };
              readonly createdAt: {
                readonly nativeType: "timestamptz";
                readonly codecId: "pg/timestamptz@1";
                readonly nullable: false;
                readonly default: {
                  readonly kind: "function";
                  readonly expression: "now()";
                };
              };
              readonly updatedAt: {
                readonly nativeType: "timestamptz";
                readonly codecId: "pg/timestamptz@1";
                readonly nullable: false;
              };
            };
            primaryKey: { readonly columns: readonly ["id"] };
            uniques: readonly [];
            indexes: readonly [
              { readonly columns: readonly ["email"] },
              { readonly columns: readonly ["createdAt"] },
            ];
            foreignKeys: readonly [];
          };
          readonly post: {
            columns: {
              readonly id: {
                readonly nativeType: "int4";
                readonly codecId: "pg/int4@1";
                readonly nullable: false;
                readonly default: {
                  readonly kind: "function";
                  readonly expression: "autoincrement()";
                };
              };
              readonly title: {
                readonly nativeType: "text";
                readonly codecId: "pg/text@1";
                readonly nullable: false;
              };
              readonly content: {
                readonly nativeType: "text";
                readonly codecId: "pg/text@1";
                readonly nullable: true;
              };
              readonly authorId: {
                readonly nativeType: "int4";
                readonly codecId: "pg/int4@1";
                readonly nullable: false;
              };
              readonly createdAt: {
                readonly nativeType: "timestamptz";
                readonly codecId: "pg/timestamptz@1";
                readonly nullable: false;
                readonly default: {
                  readonly kind: "function";
                  readonly expression: "now()";
                };
              };
              readonly updatedAt: {
                readonly nativeType: "timestamptz";
                readonly codecId: "pg/timestamptz@1";
                readonly nullable: false;
              };
            };
            primaryKey: { readonly columns: readonly ["id"] };
            uniques: readonly [];
            indexes: readonly [];
            foreignKeys: readonly [
              {
                readonly source: {
                  readonly namespaceId: "__unbound__";
                  readonly tableName: "post";
                  readonly columns: readonly ["authorId"];
                };
                readonly target: {
                  readonly namespaceId: "__unbound__";
                  readonly tableName: "user";
                  readonly columns: readonly ["id"];
                };
                readonly constraint: true;
                readonly index: true;
              },
            ];
          };
          readonly user: {
            columns: {
              readonly id: {
                readonly nativeType: "int4";
                readonly codecId: "pg/int4@1";
                readonly nullable: false;
                readonly default: {
                  readonly kind: "function";
                  readonly expression: "autoincrement()";
                };
              };
              readonly email: {
                readonly nativeType: "text";
                readonly codecId: "pg/text@1";
                readonly nullable: false;
              };
              readonly username: {
                readonly nativeType: "text";
                readonly codecId: "pg/text@1";
                readonly nullable: true;
              };
              readonly name: {
                readonly nativeType: "text";
                readonly codecId: "pg/text@1";
                readonly nullable: true;
              };
              readonly createdAt: {
                readonly nativeType: "timestamptz";
                readonly codecId: "pg/timestamptz@1";
                readonly nullable: false;
                readonly default: {
                  readonly kind: "function";
                  readonly expression: "now()";
                };
              };
              readonly updatedAt: {
                readonly nativeType: "timestamptz";
                readonly codecId: "pg/timestamptz@1";
                readonly nullable: false;
              };
            };
            primaryKey: { readonly columns: readonly ["id"] };
            uniques: readonly [{ readonly columns: readonly ["email"] }];
            indexes: readonly [];
            foreignKeys: readonly [];
          };
          readonly waitlist: {
            columns: {
              readonly id: {
                readonly nativeType: "int4";
                readonly codecId: "pg/int4@1";
                readonly nullable: false;
                readonly default: {
                  readonly kind: "function";
                  readonly expression: "autoincrement()";
                };
              };
              readonly email: {
                readonly nativeType: "text";
                readonly codecId: "pg/text@1";
                readonly nullable: false;
              };
              readonly status: {
                readonly nativeType: "text";
                readonly codecId: "pg/text@1";
                readonly nullable: false;
                readonly default: {
                  readonly kind: "literal";
                  readonly value: DefaultLiteralValue<"pg/text@1", "pending">;
                };
              };
              readonly createdAt: {
                readonly nativeType: "timestamptz";
                readonly codecId: "pg/timestamptz@1";
                readonly nullable: false;
                readonly default: {
                  readonly kind: "function";
                  readonly expression: "now()";
                };
              };
              readonly updatedAt: {
                readonly nativeType: "timestamptz";
                readonly codecId: "pg/timestamptz@1";
                readonly nullable: false;
              };
            };
            primaryKey: { readonly columns: readonly ["id"] };
            uniques: readonly [];
            indexes: readonly [
              { readonly columns: readonly ["email"] },
              { readonly columns: readonly ["createdAt"] },
            ];
            foreignKeys: readonly [];
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  },
  {
    readonly ContactForm: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/int4@1";
          };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/text@1";
          };
        };
        readonly email: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/text@1";
          };
        };
        readonly phone: {
          readonly nullable: true;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/text@1";
          };
        };
        readonly message: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/text@1";
          };
        };
        readonly status: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/text@1";
          };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/timestamptz@1";
          };
        };
        readonly updatedAt: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/timestamptz@1";
          };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: {
        readonly table: "contactForm";
        readonly fields: {
          readonly id: { readonly column: "id" };
          readonly name: { readonly column: "name" };
          readonly email: { readonly column: "email" };
          readonly phone: { readonly column: "phone" };
          readonly message: { readonly column: "message" };
          readonly status: { readonly column: "status" };
          readonly createdAt: { readonly column: "createdAt" };
          readonly updatedAt: { readonly column: "updatedAt" };
        };
      };
    };
    readonly Post: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/int4@1";
          };
        };
        readonly title: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/text@1";
          };
        };
        readonly content: {
          readonly nullable: true;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/text@1";
          };
        };
        readonly authorId: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/int4@1";
          };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/timestamptz@1";
          };
        };
        readonly updatedAt: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/timestamptz@1";
          };
        };
      };
      readonly relations: {
        readonly author: {
          readonly to: "User";
          readonly cardinality: "N:1";
          readonly on: {
            readonly localFields: readonly ["authorId"];
            readonly targetFields: readonly ["id"];
          };
        };
      };
      readonly storage: {
        readonly table: "post";
        readonly fields: {
          readonly id: { readonly column: "id" };
          readonly title: { readonly column: "title" };
          readonly content: { readonly column: "content" };
          readonly authorId: { readonly column: "authorId" };
          readonly createdAt: { readonly column: "createdAt" };
          readonly updatedAt: { readonly column: "updatedAt" };
        };
      };
    };
    readonly User: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/int4@1";
          };
        };
        readonly email: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/text@1";
          };
        };
        readonly username: {
          readonly nullable: true;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/text@1";
          };
        };
        readonly name: {
          readonly nullable: true;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/text@1";
          };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/timestamptz@1";
          };
        };
        readonly updatedAt: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/timestamptz@1";
          };
        };
      };
      readonly relations: {
        readonly posts: {
          readonly to: "Post";
          readonly cardinality: "1:N";
          readonly on: {
            readonly localFields: readonly ["id"];
            readonly targetFields: readonly ["authorId"];
          };
        };
      };
      readonly storage: {
        readonly table: "user";
        readonly fields: {
          readonly id: { readonly column: "id" };
          readonly email: { readonly column: "email" };
          readonly username: { readonly column: "username" };
          readonly name: { readonly column: "name" };
          readonly createdAt: { readonly column: "createdAt" };
          readonly updatedAt: { readonly column: "updatedAt" };
        };
      };
    };
    readonly Waitlist: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/int4@1";
          };
        };
        readonly email: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/text@1";
          };
        };
        readonly status: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/text@1";
          };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/timestamptz@1";
          };
        };
        readonly updatedAt: {
          readonly nullable: false;
          readonly type: {
            readonly kind: "scalar";
            readonly codecId: "pg/timestamptz@1";
          };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: {
        readonly table: "waitlist";
        readonly fields: {
          readonly id: { readonly column: "id" };
          readonly email: { readonly column: "email" };
          readonly status: { readonly column: "status" };
          readonly createdAt: { readonly column: "createdAt" };
          readonly updatedAt: { readonly column: "updatedAt" };
        };
      };
    };
  }
> & {
  readonly target: "postgres";
  readonly targetFamily: "sql";
  readonly roots: {
    readonly user: "User";
    readonly post: "Post";
    readonly contactForm: "ContactForm";
    readonly waitlist: "Waitlist";
  };
  readonly capabilities: {
    readonly postgres: {
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly table: "contactForm";
            readonly column: "updatedAt";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
          readonly onUpdate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
        },
        {
          readonly ref: {
            readonly table: "post";
            readonly column: "updatedAt";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
          readonly onUpdate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
        },
        {
          readonly ref: {
            readonly table: "user";
            readonly column: "updatedAt";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
          readonly onUpdate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
        },
        {
          readonly ref: {
            readonly table: "waitlist";
            readonly column: "updatedAt";
          };
          readonly onCreate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
          readonly onUpdate: {
            readonly kind: "generator";
            readonly id: "timestampNow";
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
export type Models = Contract["models"];
